# Linux
- name: Include Debian custom vars
  include_vars: ../vars/debian.yaml
  when: ansible_os_family == "Debian"

- name: Include RedHat custom vars
  include_vars: ../vars/redhat.yaml
  when: ansible_os_family == "RedHat"

# Windows
- name: Include Windows custom vars
  include_vars: ../vars/windows.yaml
  when: ansible_os_family == "Windows"

# Solaris
- name: Include Solaris custom vars
  include_vars: ../vars/solaris.yaml
  when: ansible_os_family == "Solaris"

# MacOS
- name: Include MacOS custom vars
  include_vars: ../vars/macos.yaml
  when: ansible_os_family == "Darwin"

# Linux
- name: Include Linux custom tasks
  include_tasks: linux.yaml
  when: ansible_os_family == "Debian" or ansible_os_family == "RedHat"

# Windows
- name: Include Windows custom tasks
  include_tasks: windows.yaml
  when: ansible_os_family == "Windows"

# Solaris
- name: Include Solaris custom tasks
  include_tasks: solaris.yaml
  when: ansible_os_family == "Solaris"
  args:
    apply:
      environment:
        PATH: "{{ environment_paths }}"

# macOS
- name: Include MacOS custom tasks
  include_tasks: macos.yaml
  when: ansible_os_family == "Darwin"
