- name: Download agent package
  get_url:
    url: "{{ cyware_custom_packages_installation_agent_macos_url }}"
    dest: /Users/vagrant
    validate_certs: no

- include_tasks: "installation_from_custom_packages.yml"
  when: cyware_custom_packages_installation_agent_enabled
