---
# Custom package installation
cyware_custom_packages_installation_indexer_enabled: false
cyware_custom_packages_installation_indexer_deb_url: ""
cyware_custom_packages_installation_indexer_rpm_url: ""

# Cluster Settings
indexer_version: 4.8.0

single_node: false
indexer_node_name: node-1
indexer_cluster_name: cyware
indexer_network_host: '0.0.0.0'

indexer_node_master: true
indexer_node_data: true
indexer_node_ingest: true
indexer_start_timeout: 90

indexer_cluster_nodes:
  - 127.0.0.1
indexer_discovery_nodes:
  - 127.0.0.1

local_certs_path: "{{ playbook_dir }}/indexer/certificates"

# Minimum master nodes in cluster, 2 for 3 nodes Cyware indexer cluster
minimum_master_nodes: 2

# Configure hostnames for Cyware indexer nodes
# Example es1.example.com, es2.example.com
domain_name: cyware.khulnasoft.com

indexer_sec_plugin_conf_path: /etc/cyware-indexer/opensearch-security
indexer_sec_plugin_tools_path: /usr/share/cyware-indexer/plugins/opensearch-security/tools
indexer_conf_path: /etc/cyware-indexer
indexer_index_path: /var/lib/cyware-indexer/

# Security password
indexer_custom_user: ""
indexer_custom_user_role: "admin"

# Set JVM memory limits
indexer_jvm_xms: null

indexer_http_port: 9200

indexer_admin_password: changeme
dashboard_password: changeme

# Deployment settings
generate_certs: true
perform_installation: true

indexer_nolog_sensible: true
